version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "invoices.topic.events:1:1,invoices.topic.commands:1:1,invoices.topic.command-results:1:1,invoices.topic.snapshots:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./listdao/src/main/resources/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: invoices
      MYSQL_ROOT_PASSWORD: ${DB_PASS}

  commandhandler:
    build: ./commandhandler
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_HOST_NAME}:9092

  listprojector:
    build: ./listprojector
    depends_on:
      - mysql
      - kafka
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_HOST_NAME}:9092
      DB_DRIVER: ${DB_DRIVER}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  web:
    build: ./web
    depends_on:
      - mysql
      - kafka
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_HOST_NAME}:9092
      DB_DRIVER: ${DB_DRIVER}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - 8080:8080
